export enum ErrorKeys {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_DATA = 'INVALID_DATA',
  EMPTY_BODY = 'EMPTY_BODY',
  NO_RECORD_UPDATE = 'NO_RECORD_UPDATE',
  ALREADY_UPDATED = 'ALREADY_UPDATED',
  ALREADY_EXISTS = 'ALREADY_EXISTS'
}
